# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeAndNpmTool@1
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js and npm'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Publish Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: dist
    pathtoPublish: 'dist'