# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@1 # Connect to KeyVault to get all of the secretes needed and store them as pipeline variables.
  displayName: 'KeyVault fetch'
  inputs:
    azureSubscription: 'CYPDT-Referrer-TFSPN-Deploy' # Azure DevOps Service connection name created so Azure DevOps has access to KeyVault & BlobStore.
    KeyVaultName: 'Vault-CYPDT-Dev' # Name of the KeyVault to pull secrete and config from.
    SecretsFilter: >-
      Referrer-Portal-Deployment-Token

- task: NodeAndNpmTool@1
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js and npm'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  displayName: 'npm install and build'

# Deploy
- task: AzureStaticWebApp@0
  inputs:
      app_location: "/" 
      api_location: "api"
      output_location: "dist/login-demo"
  env:
      azure_static_web_apps_api_token: $(Referrer-Portal-Deployment-Token)
# Publish Artifacts
#- task: PublishBuildArtifacts@1
#  inputs:
#    artifactName: dist
#    pathtoPublish: 'dist'